---
title: superterran
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
paginate: 100
language: en-us
words_per_minute: 200
baseurl: "/"
description: I think we agree, the past is over. –George W. Bush
cover: assets/posts/space-genetics-is-essential-making-life-in-space-work.jpeg
logo: assets/images/LogoMakr_5PUVp5.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
production_url: https://superterran.com/
source_url: https://github.com/superterran/dotcom/
CNAME: 
navigation: true
subscribers: true
twitter: superterran
facebook: doug.hatcher
github: superterran
linkedin: doughatcher
codepen: superterran
disqus: true
disqus_shortname: superterran
google_analytics: UA-71254-3
plugins_dir:
- _plugins
plugins:
- jekyll-paginate
- jekyll-feed
feed:
  path: feed.xml
